### ISSUE TITLE
Please make postinst script more defensive.

### ISSUE THREAD

**Issue by plugwash** [RPi-Distro/firmware#2]
We had a discussion on IRC today and it seems that under certain circumstances the bootloader/kernel postinst scripts can end up removing the only copy of the bootloader/kernel

The scenario we saw this in was a bootstrapping scenario and not on a Pi itself but I imagine this could also happen in other scenarios, for example if the postinst is interrupted partway through and later resumed.

So it seems like a good idea to make the code more defensive. In particular to make it check whether "/usr/share/rpikernelhack/\<file\>" actually exists before doing the remove and undivert dance on it.

**Comment by ali1234** [comment]
In my case, "/usr/share/rpikernelhack" does exist, it just doesn't contain any files.

**Comment by plugwash** [comment]
Sorry it seems part of my original post was removed by Markdown. I have now edited it to add some escaping.

Markdown is horrible for a prograrmmers discussion environment........
