### ISSUE TITLE
libraspberrypi in stretch does not install any .so files

### ISSUE THREAD

**Issue by ali1234** [RPi-Distro/firmware#3]
Comparing jessie to stretch:

Only in sysroot-jessie/opt/vc/lib: libEGL.so
Only in sysroot-jessie/opt/vc/lib: libGLESv1_CM.so
Only in sysroot-jessie/opt/vc/lib: libGLESv2.so
Only in sysroot-jessie/opt/vc/lib: libOpenVG.so
Only in sysroot-jessie/opt/vc/lib: libWFC.so

This is version 1.20170703-2 which does not seem to be uploaded here yet.

**Comment by XECDesign** [comment]
They were removed to avoid conflicts with mesa and other libraries. Check libbrcm*.

**Comment by ali1234** [comment]
libbrcm* does not exist in the archive.

**Comment by XECDesign** [comment]
I am seeing:
```
5bc7d28cac4f22dd4307f36bb534185d  opt/vc/lib/libbcm_host.so
3f40191f7959596f03640977c2e512d0  opt/vc/lib/libbrcmEGL.so
2bffb4cd471e8ed955feaf9ea9876506  opt/vc/lib/libbrcmGLESv2.so
4a4a586840dd508848ca3332fbddb1db  opt/vc/lib/libbrcmOpenVG.so
470e50f3558005a7ffb25ad165582120  opt/vc/lib/libbrcmWFC.so
```

**Comment by ali1234** [comment]
Okay but where is libEGL.so?

**Comment by XECDesign** [comment]
Replaced with libbrcmEGL.so to differentiate the old proprietary library and the open mesa library.

**Comment by ali1234** [comment]
Reported a bug against Qt requesting they use the new names: https://bugreports.qt.io/browse/QTBUG-62216

**Comment by XECDesign** [comment]
Thanks

**Comment by ali1234** [comment]
I guess we can close this. I'll link any more bug reports I have to do - probably a lot of projects have hardcoded the so names.

**Comment by ali1234** [comment]
gstreamer (an old issue of mine, but it also prevents gstreamer from using the new .so names until it gets fixed): https://bugzilla.gnome.org/show_bug.cgi?id=770987
