### ISSUE TITLE
Pre and Post scripts ignore /etc/default/raspberrypi-kernel

### ISSUE THREAD

**Issue by tigpas** [RPi-Distro/firmware#4]
Hi,

in debian/gen_bootloader_postinst_preinst.sh you have this lines:

```
cat <<EOF >> raspberrypi-kernel.postinst
if [ -f /etc/default/raspberrypi-kernel ]; then
  . /etc/default/raspberrypi-kernel
  INITRD=${INITRD:-"No"}
  export INITRD
  RPI_INITRD=${RPI_INITRD:-"No"}
  export RPI_INITRD

fi
...
EOF
```
so, you generate this snipped:
```
if [ -f /etc/default/raspberrypi-kernel ]; then
  . /etc/default/raspberrypi-kernel
  INITRD=No
  export INITRD
  RPI_INITRD=No
  export RPI_INITRD

fi
```

so, INITRD and RPI_INITRD is always "No". I think, it should be changeable via /etc/default/raspberrypi-kernel, or? I fixed it and added a patchfile to this issue: [patch.txt](https://github.com/RPi-Distro/firmware/files/1293901/patch.txt)

I did this some time:
```
-  INITRD=${INITRD:-"No"}
+  INITRD=\${INITRD:-"No"}
   export INITRD
-  RPI_INITRD=${RPI_INITRD:-"No"}
+  RPI_INITRD=\${RPI_INITRD:-"No"}
```

Regards

**Comment by XECDesign** [comment]
You're absolutely right. Very well spotted, especially since this feature hasn't been added yet.
It should be fixable just by adding using `cat <<\EOF` instead of `cat <<EOF`. I'll get it fixed tomorrow.

**Comment by XECDesign** [comment]
Ended up stealing your patch, since some parts of the script shouldn't be escaped.

Thanks.
