### ISSUE TITLE
Firmware packages for Stretch will be deprecated?

### ISSUE THREAD

**Issue by hhromic** [RPi-Distro/firmware#6]
Hi, I'm wondering if further firmware packages for `stretch` will be still released or these should be now considered deprecated?

In https://github.com/RPi-Distro/firmware/blob/debian/debian/changelog I noticed that the latest versions are being now labelled for `buster` with the latest version for `stretch` being `1.20190517-1`.

Hopefully there are still plans to keep supporting Stretch, or at least you publish one more update to address the issue in https://github.com/raspberrypi/firmware/issues/1144, which is affecting a significant number of users that for now will need to still use Stretch, i.e. RetroPie users.

Thanks in advance for the info!

**Comment by XECDesign** [comment]
I believe there may be one or two more updates to the package in stretch.

**Comment by hhromic** [comment]
Thanks for the reply!  Good to hear that indeed.
I know that probably nowadays you guys are in high priority with Buster and the new RPI4, but I hope an updated firmware package for Stretch lands sooner than later. As I mentioned there are many users affected and getting an official update would be the ideal case.
I will keep this issue open as a reminder until it lands. Thanks for the hard work!

**Comment by hhromic** [comment]
Hi, sorry to be a nuissance :(
Are there any news about updating the Stretch packages?
The following two important issues are affecting many RetroPie users (and probably non-RetroPie users as well) that can't upgrade to Buster yet:

* https://github.com/raspberrypi/firmware/issues/1144 (Bluetooth Issue)
* https://github.com/raspberrypi/firmware/issues/1166 (Video Composite Issue)

Refreshing the firmware packages for Stretch to latest would be really appreciated and helpful to calm down the situation. Thanks and really sorry for the annoyance.

**Comment by XECDesign** [comment]
No news. We're just as eager to get updated firmware into the repo for stretch and buster, but don't have anything that has been deemed stable and without any known issues yet.

**Comment by hhromic** [comment]
Thanks for the update, appreciated.
Let us know if we can help in any way.

**Comment by XECDesign** [comment]
Should be public now

**Comment by hhromic** [comment]
Thanks for the heads-up, I can confirm the firmware is up-and-running in Stretch now :)
We will be keeping an eye on the two big issues (composite and BT gamepads) in RetroPie.
Will close this issue for now, thanks again for the great work you are doing at the foundation.
