### ISSUE TITLE
How are the debs getting built?

### ISSUE THREAD

**Issue by gtrainavicius** [RPi-Distro/firmware#7]
Hello! I notice this error:

https://github.com/RPi-Distro/firmware/blob/79592f9e9f0386bb169b9f767b3312a029b8180b/debian/build_headers.sh#L3

It seems to indicate that cross-compiling on say x86_64 host is not possible? Are these scripts being executed on Raspberry Pi itself? :)

I've seen the scripts in https://github.com/RPi-Distro/nightly, are there any more repositories of interest for building these packages? I'm interested in creating custom deb files for a custom kernel build.

**Comment by XECDesign** [comment]
When the kernel is cross-compiled, it builds some binaries natively. Then when you try to build a module on arm, you'll find it will error out while trying to run those binaries. So yes, to minimise headaches, everything is built natively.

**Comment by gtrainavicius** [comment]
Are the nightly scripts the ones you use to make official releases?

**Comment by XECDesign** [comment]
The official releases are made with ./debian/update.sh, which is quite messy and makes a lot of assumptions about the build environment. It shouldn't be too incomprehensible.

This package is definitely in need of a complete overhaul.

**Comment by gtrainavicius** [comment]
Ok, thank you! :) One feature request I'd like to suggest is to have a way to rename the package or add a suffix - a few years ago I succeeded building a raspberrypi-kernel-rt package, including the 'Conflicts: raspberrypi-kernel', so that the other version of the kernel would get uninstalled automatically, it worked out quite well. (https://github.com/BlokasLabs/rpi-linux-deb)

Now it's time to update again.
