### ISSUE TITLE
[Bullseye] Changed libraspberrypi0 file names

### ISSUE THREAD

**Issue by MichaIng** [RPi-Distro/firmware#8]
We recognised that with the latest `libraspberrypi0` package on Bullseye the library filenames have changed, with `.0` appended, which broke several binaries from starting, even newly compiled ones, which are still looking for the shared objects without `.0` endings.

I know there is no official RPi OS Bullseye release yet, so no problem with breaking changes, I just wanted to ask whether this has been done with purpose and whether these names are updated in other related packages. I'm not sure how those are pulled in by e.g. Kodi, MPD, MiniDLNA and some others. Even when recompiling against current `libraspberrypi-dev`, binaries are still looking for `libmmal_core.so` instead of `libmmal_core.so.0`, so somewhere this change is still missing.

**Comment by XECDesign** [comment]
The change is intentional, but it's expected packages built agains tlibraspberrypi-dev should work with just libraspberrypi0 installed.

I'll check what's going on, thanks.

**Comment by XECDesign** [comment]
Looks okay:

```
$ wget https://github.com/raspberrypi/firmware/raw/master/hardfp/opt/vc/src/hello_pi/hello_mmal_encode/mmal_encode.c
$ cc mmal_encode.c -o mmal_encode -lpthread $(pkg-config --libs mmal)
$ ldd mmal_encode
        linux-vdso.so.1 (0xbefda000)
        /usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0xb6f28000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6ee9000)
        libmmal_core.so.0 => /lib/arm-linux-gnueabihf/libmmal_core.so.0 (0xb6eca000)
        libmmal_util.so.0 => /lib/arm-linux-gnueabihf/libmmal_util.so.0 (0xb6eab000)
        libbcm_host.so.0 => /lib/arm-linux-gnueabihf/libbcm_host.so.0 (0xb6e85000)
        libvcos.so.0 => /lib/arm-linux-gnueabihf/libvcos.so.0 (0xb6e69000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6d15000)
        /lib/ld-linux-armhf.so.3 (0xb6f3d000)
        libvchiq_arm.so.0 => /lib/arm-linux-gnueabihf/libvchiq_arm.so.0 (0xb6cfe000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6cea000)
```

How do I reproduce the issue?

**Comment by MichaIng** [comment]
```
2021-09-14 17:15:02 root@Building-ARMv6-Bullseye:~/xbmc-19.1-Matrix# ldd kodi-gbm
...
        libmmal_core.so => /usr/lib/arm-linux-gnueabihf/libmmal_core.so (0x72487000)
        libmmal_util.so => /usr/lib/arm-linux-gnueabihf/libmmal_util.so (0x72468000)
        libmmal_vc_client.so => /usr/lib/arm-linux-gnueabihf/libmmal_vc_client.so (0x7244a000)
        libbcm_host.so => /usr/lib/arm-linux-gnueabihf/libbcm_host.so (0x72424000)
        libvcsm.so => /usr/lib/arm-linux-gnueabihf/libvcsm.so (0x72407000)
...
```
This was compiled with new `libraspberrypi-dev` installed. Previously the same error happened with the old with and without `libraspberrypi-dev` even being installed, so I have no idea where these links are actually coming from.

Also we got a report where MPD failed for the same reason:
```
Sep 11 23:36:03 M-MUSIC-PLAYER systemd[1]: Starting Music Player Daemon (DietPi)...
Sep 11 23:36:04 M-MUSIC-PLAYER mpd[4284]: /usr/bin/mpd: error while loading shared libraries: libvchiq_arm.so: cannot open shared object file: No such file or directory
Sep 11 23:36:04 M-MUSIC-PLAYER systemd[1]: mpd.service: Main process exited, code=exited, status=127/n/a
Sep 11 23:36:05 M-MUSIC-PLAYER systemd[1]: mpd.service: Failed with result 'exit-code'.
Sep 11 23:36:05 M-MUSIC-PLAYER systemd[1]: Failed to start Music Player Daemon (DietPi).
```
But since the RPi repo does not ship any MPD package, this is the one from Raspbian which is not compiled at all against any RPi specific library. Same with the `minidlna` package from either Raspbian or Debian.

Found `pax-utils` > `lddtree`:
```
    libavcodec.so.58 => /usr/lib/arm-linux-gnueabihf/libavcodec.so.58
        libvpx.so.6 => /usr/lib/arm-linux-gnueabihf/libvpx.so.6
        libwebpmux.so.3 => /usr/lib/arm-linux-gnueabihf/libwebpmux.so.3
        libwebp.so.6 => /usr/lib/arm-linux-gnueabihf/libwebp.so.6
        libmmal_core.so => /usr/lib/arm-linux-gnueabihf/libmmal_core.so
            libvcos.so.0 => /usr/lib/arm-linux-gnueabihf/libvcos.so.0
        libmmal_util.so => /usr/lib/arm-linux-gnueabihf/libmmal_util.so
        libmmal_vc_client.so => /usr/lib/arm-linux-gnueabihf/libmmal_vc_client.so
            libvchiq_arm.so.0 => /usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0
            libvcsm.so.0 => /usr/lib/arm-linux-gnueabihf/libvcsm.so.0
        libbcm_host.so => /usr/lib/arm-linux-gnueabihf/libbcm_host.so
        libvcsm.so => /usr/lib/arm-linux-gnueabihf/libvcsm.so
```
So it's the FFmpeg libraries which pull in the dependency on the old patch. Makes sense as those are shipped by the RPi repo as well. Hence FFmpeg requires an update?

Okay that makes all sense then. When rebuilding FFmpeg packages, then also its good to put a min version dependency on `libraspberrypi0` so that the new filenames are present for sure.

**Comment by XECDesign** [comment]
New builds of ffmpeg and chromium-browser have been uploaded.

How and where from was kodi-gbm built? Now that the libraries are in standard paths and follow at leat some of the conventions, things generally "just work", so I'm not sure what it's doing that's different.

Either way, mmal will be removed completly at some point, so applications which still rely on legacy libraries should move away to v4l2 and libcamera.

**Comment by MichaIng** [comment]
Many thanks, the new FFmpeg packages solved everything. Kodi was compiled via:
```sh
cmake -DWITH_CPU='arm1176jzf-s' -DCORE_PLATFORM_NAME=gbm -DAPP_RENDER_SYSTEM=gles -DX11_RENDER_SYSTEM=gles -DENABLE_TESTING=OFF
```
It does not make use of libraspberrypi, it was the linked `libavcodec.so.58` which pulled in these, not Kodi directly. Same issue was with MPD, MiniDLNA and some other media software binaries which pulled in libraspberrypi indirectly via FFmpeg libraries.

Since the issue is solved, I mark this as closed.
